services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - BUILDKIT_INLINE_CACHE=1
    ports:
      - "5000:5000"
    volumes:
      - .:/acma
      - uploads:/acma/uploads